name: scCRC_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.5
  - r-base=4.3.3
  - ipykernel
  - r-devtools
  - rpy2
  - r-seurat=4.3.0.1
  - r-matrix=1.6.1.1
  - r-sctransform=0.4.0
  - r-uwot=0.1.16
  - r-seuratobject=4.1.3
  - bioconductor-gsva=1.48.2
  - r-tidyr=1.3.0
  - r-svglite=2.1.2
  - r-nloptr=2.0.3
  - r-ggrastr
  - r-cairo
  - bioconductor-clusterprofiler=4.8
  - bioconductor-org.hs.eg.db=3.17.0
  - umap-learn=0.5.4
  - pip
